[package]
name = "fon"
version = "0.2.1"
edition = "2021"
description = "Fast Object Notation - high-performance serialization core (Rust)"
license = "MIT"
repository = "https://github.com/FastObjectNotation/FON.rust"

[lib]
name = "fon"
path = "src/lib.rs"

[dependencies]
rayon = "1"
memchr = "2"
atoi = "2"

[dev-dependencies]
criterion = "0.5"
mimalloc = "0.1"

[[bench]]
name = "fon_bench"
harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
